spring.application.name=ecommerce

# SERVER PORT
server.port=8080

# RAILWAY MYSQL (PUBLIC URL)
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:35817/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fLNPMNGwFQsZqJeRobSNLCgWtVThLoEv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false


#Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=darshanl1254@gmail.com
spring.mail.password=aygc oozo prdg dtxp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Cloudinary Properties
cloudinary.cloud_name=dlkzkocq9
cloudinary.key=445575721697743
cloudinary.secret=zIGXFGZhICm4CPWx8wLWff0HL88

#Razorpay Properties
razorpay.key=rzp_test_f4vcAPoh0RDZfi
razorpay.secret=jjblWSJ6F7NJuPUOtNmDjg4i

#Admin Credentials
admin.email=admin
admin.password=admin

#For redirect to work 
server.forward-headers-strategy=FRAMEWORK

#For not checking while saving in DB
spring.jpa.properties.javax.persistence.validation.mode=none