spring.application.name=ecommerce

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

#Connection Stability (Important for Railway)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

spring.jpa.open-in-view=false
server.tomcat.connection-timeout=20000

#Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=darshanl1254@gmail.com
spring.mail.password=aygc oozo prdg dtxp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Cloudinary Properties
cloudinary.cloud_name=dlkzkocq9
cloudinary.key=445575721697743
cloudinary.secret=zIGXFGZhICm4CPWx8wLWff0HL88

#Razorpay Properties
razorpay.key=rzp_test_f4vcAPoh0RDZfi
razorpay.secret=jjblWSJ6F7NJuPUOtNmDjg4i

#Admin Credentials
admin.email=admin
admin.password=admin

#For redirect to work 
server.forward-headers-strategy=FRAMEWORK

# disable bean validation on JPA lifecycle (use jakarta namespace)
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
# or, equivalently:
# spring.jpa.properties.jakarta.persistence.validation.mode=none